"use client";

import { useUser } from "@clerk/nextjs";
import { useMutation } from "convex/react";
// @ts-ignore — generated by `npx convex dev`, not yet present
import { api } from "@/convex/_generated/api";
import { useEffect } from "react";
import { Sidebar } from "@/components/sidebar";
import { BottomTabs } from "@/components/bottom-tabs";

export default function AppLayout({ children }: { children: React.ReactNode }) {
  const { user, isLoaded } = useUser();
  const syncUser = useMutation(api.users.syncUser);

  useEffect(() => {
    if (isLoaded && user) {
      syncUser({
        clerkId: user.id,
        email: user.primaryEmailAddress?.emailAddress ?? "",
        name: user.fullName ?? user.firstName ?? "Runner",
        avatarUrl: user.imageUrl,
      });
    }
  }, [isLoaded, user, syncUser]);

  if (!isLoaded) {
    return (
      <div className="flex min-h-screen items-center justify-center">
        <div className="text-text-secondary">Loading...</div>
      </div>
    );
  }

  return (
    <div className="flex min-h-screen bg-background">
      {/* Desktop sidebar — hidden on mobile */}
      <div className="hidden md:block">
        <Sidebar />
      </div>

      {/* Main content */}
      <main className="flex-1 pb-20 md:pb-0 overflow-y-auto">
        <div className="mx-auto max-w-5xl px-4 md:px-8 py-6">
          {children}
        </div>
      </main>

      {/* Mobile bottom tabs — hidden on desktop */}
      <div className="md:hidden">
        <BottomTabs />
      </div>
    </div>
  );
}
