import { action, internalAction, internalMutation } from "./_generated/server";
// @ts-ignore — generated by `npx convex dev`, not yet present
import { internal, api } from "./_generated/api";
import { v } from "convex/values";
import { Id } from "./_generated/dataModel";

// ---------------------------------------------------------------------------
// refreshTokenIfNeeded
// Checks if the user's Strava access token is expired. If so, refreshes it
// using the refresh token and stores the new tokens. Returns the valid token.
// ---------------------------------------------------------------------------
export const refreshTokenIfNeeded = internalAction({
  args: {
    userId: v.id("users"),
  },
  handler: async (ctx, args): Promise<string> => {
    const user = await ctx.runQuery(internal.users.getById, {
      userId: args.userId,
    });

    if (!user) throw new Error("User not found");
    if (!user.stravaTokens) throw new Error("No Strava tokens found for user");

    const { accessToken, refreshToken, expiresAt } = user.stravaTokens;

    // Token is still valid — return it directly
    if (Date.now() < expiresAt) {
      return accessToken;
    }

    // Token expired — refresh it
    const clientId = process.env.STRAVA_CLIENT_ID;
    const clientSecret = process.env.STRAVA_CLIENT_SECRET;
    if (!clientId || !clientSecret) {
      throw new Error("Missing STRAVA_CLIENT_ID or STRAVA_CLIENT_SECRET env vars");
    }

    const resp = await fetch("https://www.strava.com/oauth/token", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        client_id: clientId,
        client_secret: clientSecret,
        grant_type: "refresh_token",
        refresh_token: refreshToken,
      }),
    });

    if (!resp.ok) {
      const body = await resp.text();
      throw new Error(`Strava token refresh failed: ${resp.status} ${body}`);
    }

    const data = await resp.json();

    // Persist the new tokens
    await ctx.runMutation(internal.strava.updateUserTokens, {
      userId: args.userId,
      accessToken: data.access_token,
      refreshToken: data.refresh_token,
      // Strava returns expiresAt as Unix seconds — convert to ms
      expiresAt: data.expires_at * 1000,
    });

    return data.access_token as string;
  },
});

// Internal helper to update tokens on the user record
export const updateUserTokens = internalMutation({
  args: {
    userId: v.id("users"),
    accessToken: v.string(),
    refreshToken: v.string(),
    expiresAt: v.number(),
  },
  handler: async (ctx, args) => {
    await ctx.db.patch(args.userId, {
      stravaTokens: {
        accessToken: args.accessToken,
        refreshToken: args.refreshToken,
        expiresAt: args.expiresAt,
      },
    });
  },
});

// Internal helper to stamp lastSyncAt on the user record
export const updateLastSyncAt = internalMutation({
  args: {
    userId: v.id("users"),
    lastSyncAt: v.number(),
  },
  handler: async (ctx, args) => {
    await ctx.db.patch(args.userId, { lastSyncAt: args.lastSyncAt });
  },
});

// ---------------------------------------------------------------------------
// startSync
// Client-callable action that kicks off a full or incremental Strava sync.
// Incremental when user.lastSyncAt exists, full otherwise.
// ---------------------------------------------------------------------------
export const startSync = action({
  handler: async (ctx) => {
    const identity = await ctx.auth.getUserIdentity();
    if (!identity) throw new Error("Not authenticated");

    const user = await ctx.runQuery(
      // @ts-ignore
      api.users.currentUser,
      {}
    );
    if (!user) throw new Error("User not found");

    // Guard against concurrent syncs
    const syncStatus = await ctx.runQuery(
      // @ts-ignore
      api.syncStatus.getSyncStatus,
      {}
    );
    if (syncStatus?.status === "syncing") {
      throw new Error("Sync already in progress");
    }

    // Mark sync as started
    await ctx.runMutation(internal.syncStatus.upsertSyncStatus, {
      userId: user._id,
      status: "syncing",
      syncedActivities: 0,
    });

    // Incremental if we have a prior sync timestamp, full otherwise
    const after: number | undefined = user.lastSyncAt ?? undefined;

    // Kick off the first page fetch asynchronously
    await ctx.scheduler.runAfter(0, internal.strava.fetchActivitiesPage, {
      userId: user._id,
      page: 1,
      after,
      syncedSoFar: 0,
    });
  },
});

// ---------------------------------------------------------------------------
// fetchActivitiesPage
// Internal self-scheduling action. Fetches one page (up to 200) of activities
// from the Strava API and schedules the next page if more exist.
// ---------------------------------------------------------------------------
export const fetchActivitiesPage = internalAction({
  args: {
    userId: v.id("users"),
    page: v.number(),
    after: v.optional(v.number()),
    syncedSoFar: v.number(),
  },
  handler: async (ctx, args) => {
    const { userId, page, after, syncedSoFar } = args;

    try {
      const accessToken = await ctx.runAction(
        internal.strava.refreshTokenIfNeeded,
        { userId }
      );

      // Strava's `after` param is Unix epoch in SECONDS
      const afterParam = after !== undefined
        ? `&after=${Math.floor(after / 1000)}`
        : "";

      const url =
        `https://www.strava.com/api/v3/athlete/activities` +
        `?per_page=200&page=${page}${afterParam}`;

      const resp = await fetch(url, {
        headers: { Authorization: `Bearer ${accessToken}` },
      });

      if (!resp.ok) {
        const body = await resp.text();
        throw new Error(
          `Strava activities fetch failed: ${resp.status} ${body}`
        );
      }

      const stravaActivities: any[] = await resp.json();

      // Map Strava API fields to our schema
      const mapped = stravaActivities.map((a: any) => {
        const activity: Record<string, any> = {
          stravaId: a.id,
          type: a.type ?? "Unknown",
          name: a.name ?? "Untitled",
          startDate: new Date(a.start_date).getTime(),
          distance: a.distance ?? 0,
          movingTime: a.moving_time ?? 0,
          elapsedTime: a.elapsed_time ?? 0,
          totalElevationGain: a.total_elevation_gain ?? 0,
          averageSpeed: a.average_speed ?? 0,
          maxSpeed: a.max_speed ?? 0,
          raw: a,
        };

        // Optional fields — only include if present
        if (a.description != null) activity.description = a.description;
        if (a.average_heartrate != null) activity.averageHeartrate = a.average_heartrate;
        if (a.max_heartrate != null) activity.maxHeartrate = a.max_heartrate;
        if (a.average_cadence != null) activity.averageCadence = a.average_cadence;
        if (a.calories != null) activity.calories = a.calories;
        if (Array.isArray(a.splits_metric) && a.splits_metric.length > 0) {
          activity.splits = a.splits_metric;
        }
        if (Array.isArray(a.start_latlng) && a.start_latlng.length === 2) {
          activity.startLatlng = a.start_latlng;
        }
        if (Array.isArray(a.end_latlng) && a.end_latlng.length === 2) {
          activity.endLatlng = a.end_latlng;
        }
        if (a.map?.summary_polyline != null) {
          activity.map = { summaryPolyline: a.map.summary_polyline };
        }

        return activity;
      });

      // Insert the batch — skips duplicates internally
      const inserted: number = await ctx.runMutation(
        internal.activities.batchInsert,
        { userId, activities: mapped }
      );

      const totalSynced = syncedSoFar + inserted;

      // Update progress
      await ctx.runMutation(internal.syncStatus.upsertSyncStatus, {
        userId,
        status: "syncing",
        syncedActivities: totalSynced,
      });

      if (stravaActivities.length === 200) {
        // More pages may exist — schedule the next one
        await ctx.scheduler.runAfter(0, internal.strava.fetchActivitiesPage, {
          userId,
          page: page + 1,
          after,
          syncedSoFar: totalSynced,
        });
      } else {
        // All pages fetched — mark sync complete
        const now = Date.now();
        await ctx.runMutation(internal.syncStatus.upsertSyncStatus, {
          userId,
          status: "completed",
          syncedActivities: totalSynced,
          completedAt: now,
        });
        await ctx.runMutation(internal.strava.updateLastSyncAt, {
          userId,
          lastSyncAt: now,
        });
      }
    } catch (err: any) {
      await ctx.runMutation(internal.syncStatus.upsertSyncStatus, {
        userId,
        status: "error",
        lastError: err?.message ?? "Unknown error during sync",
      });
    }
  },
});
