import { action, internalAction, internalMutation } from "./_generated/server";
// @ts-ignore — generated by `npx convex dev`, not yet present
import { internal, api } from "./_generated/api";
import { v } from "convex/values";
import { Id } from "./_generated/dataModel";

// ---------------------------------------------------------------------------
// refreshTokenIfNeeded
// Checks if the user's Strava access token is expired. If so, refreshes it
// using the refresh token and stores the new tokens. Returns the valid token.
// ---------------------------------------------------------------------------
export const refreshTokenIfNeeded = internalAction({
  args: {
    userId: v.id("users"),
  },
  handler: async (ctx, args): Promise<string> => {
    const user = await ctx.runQuery(internal.users.getById, {
      userId: args.userId,
    });

    if (!user) throw new Error("User not found");
    if (!user.stravaTokens) throw new Error("No Strava tokens found for user");

    const { accessToken, refreshToken, expiresAt } = user.stravaTokens;

    // Token is still valid — return it directly
    if (Date.now() < expiresAt) {
      return accessToken;
    }

    // Token expired — refresh it
    const clientId = process.env.STRAVA_CLIENT_ID;
    const clientSecret = process.env.STRAVA_CLIENT_SECRET;
    if (!clientId || !clientSecret) {
      throw new Error("Missing STRAVA_CLIENT_ID or STRAVA_CLIENT_SECRET env vars");
    }

    const resp = await fetch("https://www.strava.com/oauth/token", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        client_id: clientId,
        client_secret: clientSecret,
        grant_type: "refresh_token",
        refresh_token: refreshToken,
      }),
    });

    if (!resp.ok) {
      const body = await resp.text();
      throw new Error(`Strava token refresh failed: ${resp.status} ${body}`);
    }

    const data = await resp.json();

    // Persist the new tokens
    await ctx.runMutation(internal.strava.updateUserTokens, {
      userId: args.userId,
      accessToken: data.access_token,
      refreshToken: data.refresh_token,
      // Strava returns expiresAt as Unix seconds — convert to ms
      expiresAt: data.expires_at * 1000,
    });

    return data.access_token as string;
  },
});

// Internal helper to update tokens on the user record
export const updateUserTokens = internalMutation({
  args: {
    userId: v.id("users"),
    accessToken: v.string(),
    refreshToken: v.string(),
    expiresAt: v.number(),
  },
  handler: async (ctx, args) => {
    await ctx.db.patch(args.userId, {
      stravaTokens: {
        accessToken: args.accessToken,
        refreshToken: args.refreshToken,
        expiresAt: args.expiresAt,
      },
    });
  },
});

// Internal helper to stamp lastSyncAt on the user record
export const updateLastSyncAt = internalMutation({
  args: {
    userId: v.id("users"),
    lastSyncAt: v.number(),
  },
  handler: async (ctx, args) => {
    await ctx.db.patch(args.userId, { lastSyncAt: args.lastSyncAt });
  },
});

// ---------------------------------------------------------------------------
// startSync
// Client-callable action that kicks off a full or incremental Strava sync.
// Incremental when user.lastSyncAt exists, full otherwise.
// ---------------------------------------------------------------------------
export const startSync = action({
  handler: async (ctx) => {
    const identity = await ctx.auth.getUserIdentity();
    if (!identity) throw new Error("Not authenticated");

    const user = await ctx.runQuery(
      // @ts-ignore
      api.users.currentUser,
      {}
    );
    if (!user) throw new Error("User not found");

    // Guard against concurrent syncs
    const syncStatus = await ctx.runQuery(
      // @ts-ignore
      api.syncStatus.getSyncStatus,
      {}
    );
    if (syncStatus?.status === "syncing") {
      throw new Error("Sync already in progress");
    }

    // Mark sync as started
    await ctx.runMutation(internal.syncStatus.upsertSyncStatus, {
      userId: user._id,
      status: "syncing",
      syncedActivities: 0,
    });

    // Incremental if we have a prior sync timestamp, full otherwise
    const after: number | undefined = user.lastSyncAt ?? undefined;

    // Kick off the first page fetch asynchronously
    await ctx.scheduler.runAfter(0, internal.strava.fetchActivitiesPage, {
      userId: user._id,
      page: 1,
      after,
      syncedSoFar: 0,
    });
  },
});

// ---------------------------------------------------------------------------
// fetchActivitiesPage
// Internal self-scheduling action. Fetches one page (up to 200) of activities
// from the Strava API and schedules the next page if more exist.
// ---------------------------------------------------------------------------
export const fetchActivitiesPage = internalAction({
  args: {
    userId: v.id("users"),
    page: v.number(),
    after: v.optional(v.number()),
    syncedSoFar: v.number(),
  },
  handler: async (ctx, args) => {
    const { userId, page, after, syncedSoFar } = args;

    try {
      const accessToken = await ctx.runAction(
        internal.strava.refreshTokenIfNeeded,
        { userId }
      );

      // Strava's `after` param is Unix epoch in SECONDS
      const afterParam = after !== undefined
        ? `&after=${Math.floor(after / 1000)}`
        : "";

      const url =
        `https://www.strava.com/api/v3/athlete/activities` +
        `?per_page=200&page=${page}${afterParam}`;

      const resp = await fetch(url, {
        headers: { Authorization: `Bearer ${accessToken}` },
      });

      if (!resp.ok) {
        const body = await resp.text();
        throw new Error(
          `Strava activities fetch failed: ${resp.status} ${body}`
        );
      }

      const stravaActivities: any[] = await resp.json();

      // Map Strava API fields to our schema
      const mapped = stravaActivities.map((a: any) => {
        const activity: Record<string, any> = {
          stravaId: a.id,
          type: a.type ?? "Unknown",
          name: a.name ?? "Untitled",
          startDate: new Date(a.start_date).getTime(),
          distance: a.distance ?? 0,
          movingTime: a.moving_time ?? 0,
          elapsedTime: a.elapsed_time ?? 0,
          totalElevationGain: a.total_elevation_gain ?? 0,
          averageSpeed: a.average_speed ?? 0,
          maxSpeed: a.max_speed ?? 0,
          raw: a,
        };

        // Optional fields — only include if present
        if (a.description != null) activity.description = a.description;
        if (a.average_heartrate != null) activity.averageHeartrate = a.average_heartrate;
        if (a.max_heartrate != null) activity.maxHeartrate = a.max_heartrate;
        if (a.average_cadence != null) activity.averageCadence = a.average_cadence;
        if (a.calories != null) activity.calories = a.calories;
        if (Array.isArray(a.splits_metric) && a.splits_metric.length > 0) {
          activity.splits = a.splits_metric;
        }
        if (Array.isArray(a.start_latlng) && a.start_latlng.length === 2) {
          activity.startLatlng = a.start_latlng;
        }
        if (Array.isArray(a.end_latlng) && a.end_latlng.length === 2) {
          activity.endLatlng = a.end_latlng;
        }
        if (a.map?.summary_polyline != null) {
          activity.map = { summaryPolyline: a.map.summary_polyline };
        }

        return activity;
      });

      // Insert the batch — skips duplicates internally
      const { inserted, newActivities } = await ctx.runMutation(
        internal.activities.batchInsert,
        { userId, activities: mapped as any }
      ) as { inserted: number; newActivities: Array<{ stravaId: number; _id: string; type: string }> };

      const totalSynced = syncedSoFar + inserted;

      // Update progress
      await ctx.runMutation(internal.syncStatus.upsertSyncStatus, {
        userId,
        status: "syncing",
        syncedActivities: totalSynced,
      });

      // Schedule best-efforts detail fetch for newly inserted run-type activities
      const RUN_TYPES = ["Run", "TrailRun"];
      const runActivities = newActivities
        .filter((a: any) => RUN_TYPES.includes(a.type))
        .map((a: any) => ({ stravaId: a.stravaId, activityId: a._id }));

      if (runActivities.length > 0) {
        await ctx.scheduler.runAfter(0, internal.strava.fetchBestEfforts, {
          userId,
          activities: runActivities,
        });
      }

      if (stravaActivities.length === 200) {
        // More pages may exist — schedule the next one
        await ctx.scheduler.runAfter(0, internal.strava.fetchActivitiesPage, {
          userId,
          page: page + 1,
          after,
          syncedSoFar: totalSynced,
        });
      } else {
        // All pages fetched — mark sync complete
        const now = Date.now();
        await ctx.runMutation(internal.syncStatus.upsertSyncStatus, {
          userId,
          status: "completed",
          syncedActivities: totalSynced,
          completedAt: now,
        });
        await ctx.runMutation(internal.strava.updateLastSyncAt, {
          userId,
          lastSyncAt: now,
        });
      }
    } catch (err: any) {
      await ctx.runMutation(internal.syncStatus.upsertSyncStatus, {
        userId,
        status: "error",
        lastError: err?.message ?? "Unknown error during sync",
      });
    }
  },
});

// ---------------------------------------------------------------------------
// syncBestEfforts
// Client-callable action to backfill best efforts for existing activities
// that were synced before the best efforts feature was added.
// ---------------------------------------------------------------------------
export const syncBestEfforts = action({
  handler: async (ctx) => {
    const identity = await ctx.auth.getUserIdentity();
    if (!identity) throw new Error("Not authenticated");

    // @ts-ignore
    const user = await ctx.runQuery(api.users.currentUser, {});
    if (!user) throw new Error("User not found");

    // Get all run-type activities for this user
    const activities: any[] = await ctx.runQuery(
      internal.activities.listRunActivitiesForUser,
      { userId: user._id }
    );

    if (activities.length === 0) return { scheduled: 0 };

    // Get existing best effort activity IDs to skip
    const existingEfforts: any[] = await ctx.runQuery(
      internal.bestEfforts.listStravaActivityIds,
      { userId: user._id }
    );
    const existingSet = new Set(existingEfforts.map((e: any) => e.stravaActivityId));

    // Filter to activities that don't have best efforts yet
    const toFetch = activities
      .filter((a: any) => !existingSet.has(a.stravaId))
      .map((a: any) => ({ stravaId: a.stravaId, activityId: a._id }));

    if (toFetch.length === 0) return { scheduled: 0 };

    await ctx.scheduler.runAfter(0, internal.strava.fetchBestEfforts, {
      userId: user._id,
      activities: toFetch,
    });

    return { scheduled: toFetch.length };
  },
});

// ---------------------------------------------------------------------------
// fetchBestEfforts
// Self-scheduling action that fetches detailed activity data from Strava
// to extract best efforts. Processes up to 80 activities per batch.
// ---------------------------------------------------------------------------
const BEST_EFFORTS_BATCH_SIZE = 80;
const DETAIL_FETCH_DELAY_MS = 200;
const RATE_LIMIT_COOLDOWN_MS = 15 * 60 * 1000; // 15 minutes

export const fetchBestEfforts = internalAction({
  args: {
    userId: v.id("users"),
    activities: v.array(
      v.object({
        stravaId: v.number(),
        activityId: v.id("activities"),
      })
    ),
  },
  handler: async (ctx, args) => {
    const { userId, activities } = args;

    // Take up to BEST_EFFORTS_BATCH_SIZE for this batch
    const batch = activities.slice(0, BEST_EFFORTS_BATCH_SIZE);
    const remaining = activities.slice(BEST_EFFORTS_BATCH_SIZE);

    try {
      const accessToken = await ctx.runAction(
        internal.strava.refreshTokenIfNeeded,
        { userId }
      );

      for (let i = 0; i < batch.length; i++) {
        const { stravaId, activityId } = batch[i];
        try {
          const url = `https://www.strava.com/api/v3/activities/${stravaId}?include_all_efforts=true`;
          const resp = await fetch(url, {
            headers: { Authorization: `Bearer ${accessToken}` },
          });

          if (resp.status === 429) {
            // Rate limited — re-schedule remaining activities with cooldown
            const remainingFromHere = batch.slice(i).concat(remaining);
            await ctx.scheduler.runAfter(
              RATE_LIMIT_COOLDOWN_MS,
              internal.strava.fetchBestEfforts,
              { userId, activities: remainingFromHere }
            );
            return;
          }

          if (!resp.ok) {
            console.warn(`Failed to fetch detail for activity ${stravaId}: ${resp.status}`);
            continue;
          }

          const detail = await resp.json();
          const bestEfforts: any[] = detail.best_efforts ?? [];

          if (bestEfforts.length > 0) {
            const efforts = bestEfforts.map((e: any) => ({
              stravaActivityId: stravaId,
              activityId,
              name: e.name,
              distance: e.distance,
              elapsedTime: e.elapsed_time,
              movingTime: e.moving_time,
              startDate: new Date(detail.start_date).getTime(),
              ...(e.pr_rank != null ? { prRank: e.pr_rank } : {}),
            }));

            await ctx.runMutation(internal.bestEfforts.batchUpsert, {
              userId,
              efforts,
            });
          }

          // Small delay between API calls
          if (DETAIL_FETCH_DELAY_MS > 0) {
            await new Promise((r) => setTimeout(r, DETAIL_FETCH_DELAY_MS));
          }
        } catch (err: any) {
          console.warn(`Error fetching best efforts for activity ${stravaId}:`, err?.message);
        }
      }

      // Schedule next batch if more activities remain
      if (remaining.length > 0) {
        await ctx.scheduler.runAfter(
          RATE_LIMIT_COOLDOWN_MS,
          internal.strava.fetchBestEfforts,
          { userId, activities: remaining }
        );
      }
    } catch (err: any) {
      console.error("fetchBestEfforts batch failed:", err?.message);
    }
  },
});
