"use client";

import { useUser, UserButton } from "@clerk/nextjs";
import { useQuery } from "convex/react";
import { useSearchParams } from "next/navigation";
// @ts-ignore — generated by `npx convex dev`, not yet present
import { api } from "@/convex/_generated/api";
import { SyncButton } from "@/components/sync-button";

export default function ProfilePage() {
  const { user, isLoaded } = useUser();
  const convexUser = useQuery(api.users.currentUser);
  const searchParams = useSearchParams();

  const justConnected = searchParams.get("strava") === "connected";
  const authError = searchParams.get("error") === "strava_auth_failed";

  if (!isLoaded) {
    return (
      <div className="flex items-center justify-center py-20">
        <div className="text-text-secondary">Loading...</div>
      </div>
    );
  }

  const handleDeleteAccount = () => {
    const confirmed = window.confirm(
      "Are you sure you want to delete your account? This action cannot be undone."
    );
    if (confirmed) {
      // TODO: implement account deletion in a future task
      console.log("Delete account requested for user:", user?.id);
    }
  };

  return (
    <div className="max-w-xl mx-auto space-y-6 pb-8">
      <h1 className="text-2xl font-bold text-text-primary">Profile</h1>

      {/* User info card */}
      <div className="bg-surface rounded-2xl p-6 border border-border space-y-4">
        <div className="flex items-center gap-4">
          {user?.imageUrl && (
            <img
              src={user.imageUrl}
              alt={user.fullName ?? "Avatar"}
              className="w-16 h-16 rounded-full object-cover"
            />
          )}
          <div className="flex-1 min-w-0">
            <p className="text-lg font-semibold text-text-primary truncate">
              {user?.fullName ?? user?.firstName ?? "Runner"}
            </p>
            <p className="text-sm text-text-secondary truncate">
              {user?.primaryEmailAddress?.emailAddress}
            </p>
          </div>
          <UserButton />
        </div>
      </div>

      {/* Strava connection card */}
      <div className="bg-surface rounded-2xl p-6 border border-border space-y-4">
        <h2 className="text-base font-semibold text-text-primary">
          Strava Connection
        </h2>

        {authError && (
          <div className="rounded-xl bg-error/10 border border-error/20 px-4 py-3 text-sm text-error">
            Failed to connect Strava. Please try again.
          </div>
        )}

        {justConnected && (
          <div className="rounded-xl bg-success/10 border border-success/20 px-4 py-3 text-sm text-success">
            Strava connected successfully!
          </div>
        )}

        {convexUser?.stravaConnected || justConnected ? (
          <div className="space-y-4">
            <div className="flex items-center gap-3">
              {/* Connected indicator */}
              <span className="inline-flex items-center gap-2 rounded-full bg-success/10 border border-success/20 px-4 py-2 text-sm font-medium text-success">
                <span className="w-2 h-2 rounded-full bg-success inline-block" />
                Strava Connected
              </span>
            </div>
            <SyncButton />
          </div>
        ) : (
          <div className="space-y-2">
            <p className="text-sm text-text-secondary">
              Connect your Strava account to sync your runs and get AI-powered
              insights.
            </p>
            <a
              href="/api/strava/auth"
              className="inline-flex items-center gap-2 rounded-xl bg-primary px-5 py-2.5 text-sm font-semibold text-black hover:opacity-90 transition-opacity"
            >
              Connect Strava
            </a>
          </div>
        )}
      </div>

      {/* Danger zone */}
      <div className="bg-surface rounded-2xl p-6 border border-error/20 space-y-4">
        <h2 className="text-base font-semibold text-error">Danger Zone</h2>
        <p className="text-sm text-text-secondary">
          Permanently delete your account and all associated data.
        </p>
        <button
          onClick={handleDeleteAccount}
          className="rounded-xl border border-error/40 px-5 py-2.5 text-sm font-semibold text-error hover:bg-error/10 transition-colors"
        >
          Delete Account
        </button>
      </div>
    </div>
  );
}
