"use client";

import { useUser } from "@clerk/nextjs";
import { useQuery } from "convex/react";
import { useSearchParams } from "next/navigation";
// @ts-ignore — generated by `npx convex dev`, not yet present
import { api } from "@/convex/_generated/api";
import { SyncButton } from "@/components/sync-button";
import { UsageLimits } from "@/components/usage-limits";

export default function ProfilePage() {
  const { user, isLoaded } = useUser();
  const convexUser = useQuery(api.users.currentUser);
  const searchParams = useSearchParams();

  const justConnected = searchParams.get("strava") === "connected";
  const authError = searchParams.get("error") === "strava_auth_failed";

  if (!isLoaded) {
    return (
      <div className="space-y-6 pb-8">
        <div className="h-8 w-24 bg-white/5 animate-pulse rounded" />

        {/* User info card skeleton */}
        <div className="bg-[#1A1A2A] rounded-2xl p-6 border border-white/5">
          <div className="flex items-center gap-4">
            <div className="w-16 h-16 rounded-full bg-white/5 animate-pulse shrink-0" />
            <div className="flex-1 space-y-2 min-w-0">
              <div className="h-5 w-36 bg-white/5 animate-pulse rounded" />
              <div className="h-4 w-52 bg-white/5 animate-pulse rounded" />
            </div>
            <div className="w-8 h-8 rounded-full bg-white/5 animate-pulse shrink-0" />
          </div>
        </div>

        {/* Strava connection card skeleton */}
        <div className="bg-[#1A1A2A] rounded-2xl p-6 border border-white/5 space-y-4">
          <div className="h-5 w-40 bg-white/5 animate-pulse rounded" />
          <div className="flex items-center gap-3">
            <div className="h-9 w-44 bg-white/5 animate-pulse rounded-full" />
          </div>
        </div>

        {/* Danger zone skeleton */}
        <div className="bg-[#1A1A2A] rounded-2xl p-6 border border-white/5 space-y-4">
          <div className="h-5 w-28 bg-white/5 animate-pulse rounded" />
          <div className="h-4 w-72 bg-white/5 animate-pulse rounded" />
          <div className="h-9 w-36 bg-white/5 animate-pulse rounded-xl" />
        </div>
      </div>
    );
  }

  const handleDeleteAccount = () => {
    const confirmed = window.confirm(
      "Are you sure you want to delete your account? This action cannot be undone."
    );
    if (confirmed) {
      // TODO: implement account deletion in a future task
      console.log("Delete account requested for user:", user?.id);
    }
  };

  return (
    <div className="space-y-6 pb-8">
      <h1 className="text-2xl font-bold text-text-primary">Settings</h1>

      {/* Strava connection card */}
      <div className="bg-surface rounded-2xl p-6 border border-border space-y-4">
        <div className="flex items-center justify-between">
          <h2 className="text-base font-semibold text-text-primary">
            Strava Connection
          </h2>
          {(convexUser?.stravaConnected || justConnected) && (
            <span className="inline-flex items-center gap-2 rounded-full bg-success/10 border border-success/20 px-3 py-1.5 text-xs font-medium text-success">
              <span className="w-2 h-2 rounded-full bg-success inline-block" />
              Connected
            </span>
          )}
        </div>

        {authError && (
          <div className="rounded-xl bg-error/10 border border-error/20 px-4 py-3 text-sm text-error">
            Failed to connect Strava. Please try again.
          </div>
        )}

        {justConnected && (
          <div className="rounded-xl bg-success/10 border border-success/20 px-4 py-3 text-sm text-success">
            Strava connected successfully!
          </div>
        )}

        {convexUser?.stravaConnected || justConnected ? (
          <div className="space-y-4">
            <SyncButton />
          </div>
        ) : (
          <div className="space-y-2">
            <p className="text-sm text-text-secondary">
              Connect your Strava account to sync your runs and get AI-powered
              insights.
            </p>
            <a
              href="/api/strava/auth"
              className="inline-flex items-center gap-2 rounded-xl bg-primary px-5 py-2.5 text-sm font-semibold text-black hover:opacity-90 transition-opacity"
            >
              Connect Strava
            </a>
          </div>
        )}
      </div>

      {/* Usage & Limits */}
      <UsageLimits />

      {/* Danger zone */}
      <div className="bg-surface rounded-2xl p-6 border border-error/20 space-y-4">
        <h2 className="text-base font-semibold text-error">Danger Zone</h2>
        <p className="text-sm text-text-secondary">
          Permanently delete your account and all associated data.
        </p>
        <button
          onClick={handleDeleteAccount}
          className="rounded-xl border border-error/40 px-5 py-2.5 text-sm font-semibold text-error hover:bg-error/10 transition-colors"
        >
          Delete Account
        </button>
      </div>
    </div>
  );
}
