"use client";

import { useQuery, useAction, useConvexAuth } from "convex/react";
import { useState } from "react";
// @ts-ignore — generated by `npx convex dev`, not yet present
import { api } from "@/convex/_generated/api";

function relativeTime(ts: number): string {
  const diffMs = Date.now() - ts;
  const diffMins = Math.floor(diffMs / 60_000);
  if (diffMins < 1) return "just now";
  if (diffMins < 60) return `${diffMins}m ago`;
  const diffHours = Math.floor(diffMins / 60);
  if (diffHours < 24) return `${diffHours}h ago`;
  const diffDays = Math.floor(diffHours / 24);
  return `${diffDays}d ago`;
}

export function SyncButton() {
  const { isAuthenticated } = useConvexAuth();
  const syncStatus = useQuery(api.syncStatus.getSyncStatus);
  const startSync = useAction(api.strava.startSync);
  const [localError, setLocalError] = useState<string | null>(null);

  const handleSync = async () => {
    setLocalError(null);
    try {
      await startSync({});
    } catch (err: any) {
      setLocalError(err?.message ?? "Failed to start sync");
    }
  };

  const isSyncing = syncStatus?.status === "syncing";
  const isCompleted = syncStatus?.status === "completed";
  const isError = syncStatus?.status === "error" || localError !== null;
  const errorMessage =
    localError ?? syncStatus?.lastError ?? "An error occurred during sync";
  const completedAt = syncStatus?.completedAt;
  const syncedActivities = syncStatus?.syncedActivities ?? 0;

  return (
    <div className="space-y-3">
      {isError && (
        <p className="text-sm text-error">{errorMessage}</p>
      )}

      {isSyncing && (
        <div className="space-y-1.5">
          <div className="flex items-center justify-between">
            <span className="text-sm font-medium text-text-primary">Syncing...</span>
            <span className="text-xs text-text-secondary">{syncedActivities} activities synced</span>
          </div>
          {/* Indeterminate progress bar */}
          <div className="h-1.5 w-full overflow-hidden rounded-full bg-surface border border-border">
            <div className="h-full w-1/3 rounded-full bg-primary animate-[slide_1.4s_ease-in-out_infinite]" />
          </div>
        </div>
      )}

      {isCompleted && completedAt && (
        <p className="text-xs text-text-secondary">
          Last synced: {relativeTime(completedAt)}
          {syncedActivities > 0 && ` · ${syncedActivities} activities`}
        </p>
      )}

      {!isSyncing && (
        <button
          onClick={handleSync}
          disabled={!isAuthenticated}
          className={`inline-flex items-center gap-2 rounded-xl px-5 py-2.5 text-sm font-semibold transition-opacity disabled:cursor-not-allowed disabled:opacity-60 ${
            isError
              ? "bg-error/10 border border-error/40 text-error hover:bg-error/20"
              : "bg-primary text-black hover:opacity-90"
          }`}
        >
          {isError ? "Retry" : "Sync Strava"}
        </button>
      )}

      {!isAuthenticated && (
        <p className="text-xs text-text-secondary">Sign in to sync your activities.</p>
      )}
    </div>
  );
}
