"use client";

import { useQuery, useAction } from "convex/react";
import { useState } from "react";
// @ts-ignore — generated by `npx convex dev`, not yet present
import { api } from "@/convex/_generated/api";

function relativeTime(ts: number): string {
  const diffMs = Date.now() - ts;
  const diffMins = Math.floor(diffMs / 60_000);
  if (diffMins < 1) return "just now";
  if (diffMins < 60) return `${diffMins}m ago`;
  const diffHours = Math.floor(diffMins / 60);
  if (diffHours < 24) return `${diffHours}h ago`;
  const diffDays = Math.floor(diffHours / 24);
  return `${diffDays}d ago`;
}

export function SyncButton() {
  const syncStatus = useQuery(api.syncStatus.getSyncStatus);
  const startSync = useAction(api.strava.startSync);
  const [localError, setLocalError] = useState<string | null>(null);

  const handleSync = async () => {
    setLocalError(null);
    try {
      await startSync({});
    } catch (err: any) {
      setLocalError(err?.message ?? "Failed to start sync");
    }
  };

  const isSyncing = syncStatus?.status === "syncing";
  const isError = syncStatus?.status === "error" || localError !== null;
  const errorMessage =
    localError ?? syncStatus?.lastError ?? "An error occurred during sync";
  const completedAt = syncStatus?.completedAt;

  return (
    <div className="space-y-2">
      {isError && (
        <p className="text-sm text-error">{errorMessage}</p>
      )}

      {syncStatus?.status === "completed" && completedAt && (
        <p className="text-xs text-text-secondary">
          Last synced: {relativeTime(completedAt)}
        </p>
      )}

      <button
        onClick={handleSync}
        disabled={isSyncing}
        className={`inline-flex items-center gap-2 rounded-xl px-5 py-2.5 text-sm font-semibold transition-opacity disabled:cursor-not-allowed disabled:opacity-60 ${
          isError
            ? "bg-error/10 border border-error/40 text-error hover:bg-error/20"
            : "bg-primary text-black hover:opacity-90"
        }`}
      >
        {isSyncing ? (
          <>
            <span className="inline-block w-3.5 h-3.5 border-2 border-black/30 border-t-black rounded-full animate-spin" />
            Syncing...{" "}
            {syncStatus.syncedActivities > 0
              ? `${syncStatus.syncedActivities} activities`
              : ""}
          </>
        ) : isError ? (
          "Retry"
        ) : (
          "Sync Strava"
        )}
      </button>
    </div>
  );
}
