import { auth } from "@clerk/nextjs/server";
import { cookies } from "next/headers";
import { NextRequest, NextResponse } from "next/server";
import { ConvexHttpClient } from "convex/browser";
// @ts-ignore — generated by `npx convex dev`, not yet present
import { api } from "@/convex/_generated/api";

const convex = new ConvexHttpClient(process.env.NEXT_PUBLIC_CONVEX_URL!);

export async function GET(req: NextRequest) {
  try {
    const { userId } = await auth();
    console.log("[strava-callback] userId:", userId);
    if (!userId) {
      return new Response("Unauthorized", { status: 401 });
    }

    const code = req.nextUrl.searchParams.get("code");
    const state = req.nextUrl.searchParams.get("state");
    const cookieStore = await cookies();
    const storedState = cookieStore.get("strava_oauth_state")?.value;

    console.log("[strava-callback] state match:", { state: state?.slice(0, 8), storedState: storedState?.slice(0, 8) });

    // CSRF validation — reject if state is missing or doesn't match the cookie
    if (!state || !storedState || state !== storedState) {
      console.error("[strava-callback] CSRF validation failed — state mismatch");
      return NextResponse.redirect(new URL("/profile?error=csrf_failed", req.url));
    }

    // Clear state cookie immediately after validation to prevent replay
    cookieStore.delete("strava_oauth_state");

    if (!code) {
      return NextResponse.redirect(new URL("/profile?error=no_code", req.url));
    }

    // Exchange code for tokens
    console.log("[strava-callback] Exchanging code for tokens...");
    const tokenRes = await fetch("https://www.strava.com/oauth/token", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        client_id: process.env.NEXT_PUBLIC_STRAVA_CLIENT_ID,
        client_secret: process.env.STRAVA_CLIENT_SECRET,
        code,
        grant_type: "authorization_code",
      }),
    });

    if (!tokenRes.ok) {
      const errorBody = await tokenRes.text();
      console.error("[strava-callback] Token exchange failed:", tokenRes.status, errorBody);
      return NextResponse.redirect(new URL("/profile?error=token_exchange_failed", req.url));
    }

    const tokens = await tokenRes.json();
    console.log("[strava-callback] Tokens received, storing in Convex...");

    // Store tokens in Convex — uses connectStravaInternal which skips Convex auth
    // since this route is already authenticated via Clerk middleware
    await convex.mutation(api.users.connectStravaInternal, {
      clerkId: userId,
      accessToken: tokens.access_token,
      refreshToken: tokens.refresh_token,
      expiresAt: tokens.expires_at,
    });

    console.log("[strava-callback] Success!");
    return NextResponse.redirect(new URL("/profile?strava=connected", req.url));
  } catch (error) {
    console.error("[strava-callback] Error:", error);
    return NextResponse.redirect(new URL("/profile?error=strava_auth_failed", req.url));
  }
}
